[package]
name = "surrealkv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
tokio = { version = "1.32", features = ["full"] }

[dev-dependencies]
tempdir = "0.3"
