[package]
name = "surrealkv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
crossbeam = "0.8.2"
chrono = "0.4.31"
crossbeam-channel = "0.5.8"
parking_lot = "0.12.1"
hashbrown = "0.14.2"
lru = "0.12.0"
async-channel = "2.1.1"
futures = "0.3.30"
async-std = "1.12.0"
bytes = "1.5.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

# below is for the async runtime
async-task = "4.4.0"
futures-lite = "1.12.0"
once_cell = "1.17.1"
flume = "0.11.0"

tempfile = "3.5.0"
# for backwards compatibility testing - pin at 1.0.0
redb = "1.5.0"

# Just benchmarking dependencies
ctrlc = "3.2.3"
lmdb-rkv = "0.14.0"
sanakirja = "1.3.3"
sled = "0.34.7"
rocksdb = "0.21.0"
libc = "0.2.99"
comfy-table = "7.0.1"


tempdir = "0.3"
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["async_tokio", "html_reports"] }
jemallocator = "0.5.4"
nanoid = "0.4.0"
caches = "0.2" 
fastrand = "2.0.1"



[[bench]]
name = "store_bench"
harness = false
